# .gitpod.yml
image: gitpod/workspace-full

tasks:
  - name: Setup & Build
    init: |
      # 1) Start Docker
      sudo docker-up

      # 2) Install system dependencies
      sudo apt-get update
      sudo apt-get install -y pkg-config libssl-dev build-essential

      # 3) (Re)install Rust toolchain if needed
      rustup default stable

      # 4) Install Foundry
      curl -L https://foundry.paradigm.xyz | bash
      source ~/.foundry/bin

      # 5) Install RISC Zero toolchain
      curl -L https://risczero.com/install | bash
      rzup install

      # 6) Init submodules & build everything
      git submodule update --init --recursive
      cargo build               # build zkVM program & publisher
      forge build               # compile Solidity contracts

  - name: Run Tests with Local Prover
    command: |
      # Ensure full prover (no Bonsai)
      export RISC0_DEV_MODE=false
      # Run Solidity + zkVM integration tests
      forge test -vvv
